### ISSUE TITLE
Not able to install pod

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [MixinMessenger/ios-app#31]
![screen shot 2018-05-24 at 2 52 58 pm](https://user-images.githubusercontent.com/6416095/40476659-34ef23bc-5f62-11e8-85b3-9d4d0135ea41.png)

Not able to install this app. Kindly help.

**Comment by wuyuehyang** [comment]
Make sure your ssh is well configured for Github cloning.
Try git clone git@github.com:MixinMessenger/SignalProtocolC.git to locate the problem.
