### ISSUE TITLE
[Feature Request] Tap to enlarge the avatar.

### ISSUE THREAD

**Issue by lyricat** [MixinMessenger/ios-app#61]
### Step 1: Are you in the right place?

Yes. 

Avatar is an important feature for a social App. For example, Mint's avatar is so adorable and attractive that people are more and more willing to talk to her if they can see the details about her avatar, which increases the network effect.

### Step 2: Describe your environment

  * Device: iPhone X
  * OS version: iOS 11
  * App version: 0.5.5(144)
  
#### Steps to reproduce:

  1. tap user name in conversation
  2. pop up user profile pane
  3. tap user avatar
  
#### Observed Results:

  * nothing happens
  
#### Expected results

* tap the avatar in user profile bottom sheet
* popup new view to show large picture of user avatar

**Comment by cedricfung** [comment]
Already in development
