### ISSUE TITLE
WCDB.Swift error build

### ISSUE THREAD

**Issue by danen396** [MixinMessenger/ios-app#68]
![screen shot 2018-07-12 at 10 24 50 pm](https://user-images.githubusercontent.com/24821941/42639417-814be07e-8622-11e8-8b60-07188e3cd6d4.png)
![screen shot 2018-07-12 at 10 25 07 pm](https://user-images.githubusercontent.com/24821941/42639418-81821342-8622-11e8-8c6d-62f07c9a7b07.png)
![screen shot 2018-07-12 at 10 25 18 pm](https://user-images.githubusercontent.com/24821941/42639419-81c1e3aa-8622-11e8-9542-bad4a81d2710.png)

these are the error i get when i run. how do i fix it?

**Comment by crossle** [comment]
Require Xcode 9.2 Swift 4.0

**Comment by danen396** [comment]
i am using Xcode 9.2 Swift 4.0
![screen shot 2018-07-12 at 10 31 47 pm](https://user-images.githubusercontent.com/24821941/42639779-6db95450-8623-11e8-9f6f-9a31d21d4a5d.png)

**Comment by crossle** [comment]
Plz use Swift 4.0 toolchain

**Comment by danen396** [comment]
please assist me on what should i do after i install swift 4.0 toolchain?

**Comment by crossle** [comment]
If you use Xcode 9.2, it’s include swift 4.0

**Comment by danen396** [comment]
![screen shot 2018-07-12 at 11 14 56 pm](https://user-images.githubusercontent.com/24821941/42642419-6c4a4b8c-8629-11e8-82a5-18ad384afe71.png)
this is what i see

**Comment by danen396** [comment]
sorry for opening for toolchain issue but you seem to close the issue before i have completed my issue. PLEASE be clear on your instructions. i have no choice but to open an issue if i fail to understand u

**Comment by crossle** [comment]
Plz see issue template https://github.com/MixinMessenger/ios-app/blob/master/ISSUE_TEMPLATE.md

**Comment by danen396** [comment]
OMG why dont you explain it here......

**Comment by aloveric** [comment]
@danen396 Same issue. How to fix it?
